vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
        profil_image:
            uri_prefix: /uploads/profil
            upload_destination: '%kernel.project_dir%/public/uploads/profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
